/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javafx.scene.input.DataFormat; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import projeto.jdbc.ConnectFactory;
import projeto.model.Funcionarios;
import projeto.dao.FuncionarioDAO;

/**
 *
 * @author vasco
 */
public class frmVisualizarFuncionarios extends javax.swing.JFrame {
      int id;
       frmFuncionarios frm = new frmFuncionarios();
      
      
    /**
     * Creates new form frmVisualizarCadastro
     */
    public frmVisualizarFuncionarios() {
        initComponents();
        
   
           DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(new Color(32, 136, 203));

for (int i = 0; i < tabelafun.getModel().getColumnCount(); i++) {
       tabelafun.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
} 

     //JTableHeader jtab = jtablecad.getTableHeader();
    tabelafun.setForeground(new Color(255,255,255));
    tabelafun.setFont(new Font("Segoe UI", Font.BOLD, 18));
    tabelafun.getTableHeader().setOpaque(false);
    tabelafun.setRowHeight(25);
    }
     public Connection conn = null;
     
    public void povoarTabela(){
       
     
        
        
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionarios> lista = dao.listarFuncionarios();
        DefaultTableModel dados = (DefaultTableModel) tabelafun.getModel();
        dados.setNumRows(0);

        for (Funcionarios c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getUser(),
                c.getCargo(),
                c.getNivelacesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getUf()
          });

      }
           
            
  
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafun = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Pesquisar por CPF:");

        tabelafun.setBackground(new java.awt.Color(153, 153, 153));
        tabelafun.setForeground(new java.awt.Color(153, 153, 153));
        tabelafun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "CPF", "Email", "Cargo", "Nivel de Acesso", "Telefone", "Celular", "Cep", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "Uf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelafun.setFocusable(false);
        tabelafun.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelafun.setRowHeight(25);
        tabelafun.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabelafun.getTableHeader().setReorderingAllowed(false);
        tabelafun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafun);
        if (tabelafun.getColumnModel().getColumnCount() > 0) {
            tabelafun.getColumnModel().getColumn(15).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        povoarTabela();
    }//GEN-LAST:event_formWindowOpened

    private void tabelafunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafunMouseClicked
        //int lin = tabelafun.getSelectedRow();
         
        // txtID.setText(tabelafun.getValueAt(lin, 0).toString());
        
         frm.txtCodigo.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 0).toString());
        frm.txtNome.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 1).toString());
        frm.txtRG.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 2).toString());
        frm.txtCPF.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 3).toString());
        frm.txtEmail.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 4).toString());
        frm.txtCargo.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 5).toString());
        frm.cmbAcesso.setSelectedItem(tabelafun.getValueAt(tabelafun.getSelectedRow(), 6).toString());
        frm.txtTelefone.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 7).toString());
        frm.txtCelular.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 8).toString());
        frm.txtCEP.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 9).toString());
        frm.txtEndereco.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 10).toString());
        frm.txtNumero.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 11).toString());
        frm.txtComplemento.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 12).toString());
        frm.txtBairro.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 13).toString());
        frm.txtCidade.setText(tabelafun.getValueAt(tabelafun.getSelectedRow(), 14).toString());
        frm.cmbUF.setSelectedItem(tabelafun.getValueAt(tabelafun.getSelectedRow(), 15).toString());
        
        
        frm.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_tabelafunMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
                  this.dispose(); 
                           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
        
        
         String cpf = "%" +txtCPF.getText()+"%";
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionarios> lista = dao.BuscarFuncionario(cpf);
        DefaultTableModel dados = (DefaultTableModel) tabelafun.getModel();
        dados.setNumRows(0);

        for (Funcionarios c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getUser(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            });
        
        }   
    }//GEN-LAST:event_txtCPFKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     povoarTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisualizarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelafun;
    private javax.swing.JFormattedTextField txtCPF;
    // End of variables declaration//GEN-END:variables
}
