/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javafx.scene.input.DataFormat; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import projeto.dao.FornecedorDAO;
import projeto.jdbc.ConnectFactory;
import projeto.model.Funcionarios;
import projeto.dao.FuncionarioDAO;
import projeto.model.Fornecedores;

/**
 *
 * @author vasco
 */
public class frmVisualizarFornecedor extends javax.swing.JFrame {
      int id;
       frmFornecedor frm = new frmFornecedor();
      
      
    /**
     * Creates new form frmVisualizarCadastro
     */
    public frmVisualizarFornecedor() {
        initComponents();
        
   
           DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(new Color(32, 136, 203));

for (int i = 0; i < tabelafor.getModel().getColumnCount(); i++) {
       tabelafor.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
} 

     //JTableHeader jtab = jtablecad.getTableHeader();
    tabelafor.setForeground(new Color(255,255,255));
   tabelafor.setFont(new Font("Segoe UI", Font.BOLD, 18));
    tabelafor.getTableHeader().setOpaque(false);
    tabelafor.setRowHeight(25);
    }
     public Connection conn = null;
     
    public void povoarTabela(){
       
     
        
        
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedores> lista = dao.listarFornecedores();
         DefaultTableModel dados = (DefaultTableModel) tabelafor.getModel();
        dados.setNumRows(0);

        for (Fornecedores c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getUser(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            });

        }

      }
           
            
  
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafor = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Pesquisar por CPF:");

        tabelafor.setBackground(new java.awt.Color(153, 153, 153));
        tabelafor.setForeground(new java.awt.Color(153, 153, 153));
        tabelafor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNPJ", "Email", "Telefone", "Celular", "Cep", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "Uf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelafor.setFocusable(false);
        tabelafor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelafor.setRowHeight(25);
        tabelafor.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabelafor.getTableHeader().setReorderingAllowed(false);
        tabelafor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaforMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafor);
        if (tabelafor.getColumnModel().getColumnCount() > 0) {
            tabelafor.getColumnModel().getColumn(0).setResizable(false);
            tabelafor.getColumnModel().getColumn(1).setResizable(false);
            tabelafor.getColumnModel().getColumn(2).setResizable(false);
            tabelafor.getColumnModel().getColumn(3).setResizable(false);
            tabelafor.getColumnModel().getColumn(4).setResizable(false);
            tabelafor.getColumnModel().getColumn(5).setResizable(false);
            tabelafor.getColumnModel().getColumn(6).setResizable(false);
            tabelafor.getColumnModel().getColumn(7).setResizable(false);
            tabelafor.getColumnModel().getColumn(8).setResizable(false);
            tabelafor.getColumnModel().getColumn(9).setResizable(false);
            tabelafor.getColumnModel().getColumn(10).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        try {
            txtPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1284, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        povoarTabela();
    }//GEN-LAST:event_formWindowOpened

    private void tabelaforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaforMouseClicked
        //int lin = tabelafun.getSelectedRow();
         
        // txtID.setText(tabelafun.getValueAt(lin, 0).toString());
        
         frm.txtCodigo.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 0).toString());
        frm.txtNome.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 1).toString());
        frm.txtcnpj.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 2).toString());
        frm.txtEmail.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 3).toString());
        frm.txtTelefone.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 4).toString());
        frm.txtCelular.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 5).toString());
        frm.txtCEP.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 6).toString());
        frm.txtEndereco.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 7).toString());
        frm.txtNumero.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 8).toString());
        frm.txtComplemento.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 9).toString());
        frm.txtBairro.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 10).toString());
        frm.txtCidade.setText(tabelafor.getValueAt(tabelafor.getSelectedRow(), 11).toString());
        frm.cmbUF.setSelectedItem(tabelafor.getValueAt(tabelafor.getSelectedRow(), 12).toString());
        
        
        frm.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_tabelaforMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
                  this.dispose(); 
                           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        
        
       String cnpj = "%" +txtPesquisa.getText()+"%";
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedores> lista = dao.buscarFornecedores(cnpj);
        DefaultTableModel dados = (DefaultTableModel) tabelafor.getModel();
        dados.setNumRows(0);
        for (Fornecedores c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getUser(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            });

        }  
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
             povoarTabela();    


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisualizarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelafor;
    private javax.swing.JFormattedTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
